import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Mom's spaghetti",
    description: "Generated by Slim Shady",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const pages = await getPages();

    return (
        <html lang="en">
            <body className="max-w-5xl mx-auto py-10 px-4">
                <header className="flex items-center justify-between ">
                    <Link
                        href="/"
                        className="text-lg font-bold bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent hover:from-purple-600 hover:to-orange-400 transition-all"
                    >
                        SLMSHDy
                    </Link>
                    <div className="flex items-center gap-5 text-sm text-gray-600">
                        {pages.map((page) => (
                            <Link
                                key={page._id}
                                href={`/${page.slug}`}
                                className="text-lg text-black hover:text-pink-500 transition-all"
                            >
                                {page.title}
                            </Link>
                        ))}
                    </div>
                </header>
                <main className="py-20">{children}</main>
            </body>
        </html>
    );
}
