import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Mom's spaghetti",
    description: "Generated by Slim Shady",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="p-0 m-0 min-h-[100vh] relative pb-14">
                <div className="max-w-7xl mx-auto pt-10 pb-16 px-4">
                    {Header()}
                    <main className="py-20">{children}</main>
                </div>

                {Footer()}
            </body>
        </html>
    );
}
